/**
 * fetchRedditImages.js
 *
 * Local dev/admin script to populate or replenish the images table.
 * Always append-only — never drops the table.
 *
 * Usage:
 *   node fetchRedditImages.js
 *   node fetchRedditImages.js --window month
 *   node fetchRedditImages.js --subreddit EarthPorn --type Real --window year
 *   node fetchRedditImages.js --pages 4
 *
 * Generates: images_append.sql  (safe to apply with: wrangler d1 execute unvaildb --file=images_append.sql)
 */

const fs = require('fs');

// --- CLI argument parsing ---
const args = process.argv.slice(2);
const getArg = (flag) => {
    const idx = args.indexOf(flag);
    return idx !== -1 ? args[idx + 1] : null;
};

const CONFIG = {
    sources: [
        { subreddit: getArg('--subreddit') || 'itookapicture', type: getArg('--type') || 'Real' },
        { subreddit: getArg('--subreddit') ? null : 'midjourney',   type: 'AI' },
    ].filter(s => s.subreddit !== null),

    timeWindow:  getArg('--window') || 'week',   // week | month | year | all
    pages:       parseInt(getArg('--pages') || '2', 10),  // Reddit pages to fetch per source
    postsPerPage: 100,
    outputFile:  'images_append.sql',
};

const FETCH_OPTIONS = {
    headers: {
        'User-Agent': 'unvAIl-GameBuilder/2.0 (local admin script; appending to DB)'
    }
};

/**
 * Fetches image posts from a subreddit, paginating through multiple pages.
 * Returns deduplicated { url, type, explanation } objects.
 */
async function fetchFromReddit(subreddit, imageType) {
    console.log(`\nFetching "${imageType}" images from r/${subreddit} (t=${CONFIG.timeWindow}, ${CONFIG.pages} page(s))...`);

    const seen = new Set();
    const images = [];
    let after = null;

    for (let page = 0; page < CONFIG.pages; page++) {
        const url = `https://www.reddit.com/r/${subreddit}/top.json?t=${CONFIG.timeWindow}&limit=${CONFIG.postsPerPage}${after ? `&after=${after}` : ''}`;

        try {
            const response = await fetch(url, FETCH_OPTIONS);
            if (!response.ok) {
                console.warn(`  ⚠️  Reddit returned ${response.status} on page ${page + 1}. Stopping.`);
                break;
            }

            const json = await response.json();
            const posts = json?.data?.children || [];

            for (const post of posts) {
                const data = post.data;
                const imgUrl = data.url || '';

                // Only direct image links
                if (!imgUrl.match(/\.(jpg|jpeg|png|webp)(\?.*)?$/i)) continue;

                // Deduplicate within this run
                if (seen.has(imgUrl)) continue;
                seen.add(imgUrl);

                const author = data.author || 'unknown';
                const title  = (data.title || '').replace(/'/g, "''");

                const explanation = imageType === 'Real'
                    ? `Real photo by u/${author} on r/${subreddit}. Original title: "${title}"`
                    : `AI generated by u/${author} on r/${subreddit}. Original prompt/title: "${title}"`;

                images.push({ url: imgUrl, type: imageType, explanation });
            }

            after = json?.data?.after;
            if (!after) {
                console.log(`  Page ${page + 1}: ${posts.length} posts (no more pages)`);
                break;
            }

            console.log(`  Page ${page + 1}: ${posts.length} posts, continuing...`);

            // Polite delay between pages
            await new Promise(r => setTimeout(r, 1000));

        } catch (err) {
            console.error(`  ❌ Error on page ${page + 1}:`, err.message);
            break;
        }
    }

    console.log(`  ✅ Found ${images.length} candidate images from r/${subreddit}`);
    return images;
}

/**
 * Main
 */
async function main() {
    console.log('=== unvAIl Image Append Script ===');
    console.log(`Time window: ${CONFIG.timeWindow} | Pages per source: ${CONFIG.pages}`);
    console.log('Output: append-only SQL (no DROP TABLE, no CREATE TABLE)\n');

    const allImages = [];

    for (const source of CONFIG.sources) {
        const images = await fetchFromReddit(source.subreddit, source.type);
        allImages.push(...images);
    }

    if (allImages.length === 0) {
        console.error('\n❌ No images found. Check your network connection or try different flags.');
        process.exit(1);
    }

    // Shuffle so Real and AI images interleave
    for (let i = allImages.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [allImages[i], allImages[j]] = [allImages[j], allImages[i]];
    }

    // Build SQL — append-only, skips duplicates via INSERT OR IGNORE
    // Requires a UNIQUE constraint on images.url (or the caller handles deduplication).
    // Since D1/SQLite doesn't let us add UNIQUE to existing columns easily,
    // we use a subquery guard: INSERT ... WHERE NOT EXISTS (SELECT 1 FROM images WHERE url = '...').
    let sql = `-- Append-only image inserts generated by fetchRedditImages.js
-- Generated: ${new Date().toISOString()}
-- Source window: ${CONFIG.timeWindow}
-- Total candidates: ${allImages.length}
-- Apply with: wrangler d1 execute unvaildb --remote --file=${CONFIG.outputFile}

`;

    let insertCount = 0;
    for (const img of allImages) {
        // Guard against duplicates using a NOT EXISTS subquery (works on any SQLite)
        const safeUrl  = img.url.replace(/'/g, "''");
        const safeType = img.type.replace(/'/g, "''");
        const safeExp  = img.explanation.replace(/'/g, "''");

        sql += `INSERT INTO images (url, type, explanation, fetched_at, is_active, use_count)\n`;
        sql += `SELECT '${safeUrl}', '${safeType}', '${safeExp}', datetime('now'), 1, 0\n`;
        sql += `WHERE NOT EXISTS (SELECT 1 FROM images WHERE url = '${safeUrl}');\n`;
        insertCount++;
    }

    sql += `\n-- End of append. ${insertCount} conditional inserts.\n`;

    fs.writeFileSync(CONFIG.outputFile, sql, 'utf8');

    console.log(`\n🎉 Done! Written ${insertCount} conditional inserts to ${CONFIG.outputFile}`);
    console.log(`\nApply to production DB with:`);
    console.log(`  wrangler d1 execute unvaildb --remote --file=${CONFIG.outputFile}`);
    console.log(`\nThen trigger daily set pre-population:`);
    console.log(`  curl -X POST https://your-worker.workers.dev/api/admin/trigger \\`);
    console.log(`    -H "Authorization: Bearer <ADMIN_TOKEN>" \\`);
    console.log(`    -d '{"action":"prepopulate","daysAhead":30}'`);
}

main().catch(err => {
    console.error('Fatal error:', err);
    process.exit(1);
});
