const fs = require('fs');

// Configuration
const CONFIG = {
    realSubreddit: 'itookapicture', // Other good ones: EarthPorn, photocritique
    aiSubreddit: 'midjourney',      // Other good ones: StableDiffusion, AIArt
    imagesPerType: 75,
    imagesPerDay: 5
};

// Reddit requires a User-Agent header
const fetchOptions = {
    headers: {
        'User-Agent': 'RealOrAIGameBuilder/1.0 (script to populate personal game DB)'
    }
};

/**
 * Fetches image posts from a specific subreddit
 */
async function fetchImages(subreddit, type, targetCount) {
    console.log(`Fetching ${type} images from r/${subreddit}...`);

    // We request 100 posts hoping to find at least 75 direct images (filtering out text/videos)
    const url = `https://www.reddit.com/r/${subreddit}/top.json?t=all&limit=100`;

    try {
        const response = await fetch(url, fetchOptions);
        if (!response.ok) throw new Error(`Reddit API returned ${response.status}`);

        const json = await response.json();
        const posts = json.data.children;

        const validImages = [];

        for (const post of posts) {
            const data = post.data;
            const url = data.url;

            // Only keep direct image links
            if (url && (url.endsWith('.jpg') || url.endsWith('.png') || url.endsWith('.jpeg'))) {

                // Format the explanation to respect IP and give credit
                const author = data.author;
                const title = data.title;

                // Escape single quotes for SQL
                const safeTitle = title.replace(/'/g, "''");
                let explanation = '';

                if (type === 'Real') {
                    explanation = `Real photo by u/${author} on r/${subreddit}. Original title: "${safeTitle}"`;
                } else {
                    explanation = `AI generated by u/${author} on r/${subreddit}. Original prompt/title: "${safeTitle}"`;
                }

                validImages.push({ url, type, explanation });

                if (validImages.length === targetCount) break;
            }
        }

        console.log(`✅ Found ${validImages.length} usable images from r/${subreddit}`);
        return validImages;

    } catch (err) {
        console.error(`❌ Failed to fetch from r/${subreddit}:`, err);
        return [];
    }
}

/**
 * Shuffles an array in place (Fisher-Yates algorithm)
 */
function shuffleArray(array) {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
    return array;
}

/**
 * Main execution
 */
async function main() {
    console.log('Starting data generation pipeline...\n');

    const realImages = await fetchImages(CONFIG.realSubreddit, 'Real', CONFIG.imagesPerType);
    const aiImages = await fetchImages(CONFIG.aiSubreddit, 'AI', CONFIG.imagesPerType);

    // Combine and shuffle to make the game unpredictable
    const allImages = shuffleArray([...realImages, ...aiImages]);

    if (allImages.length < (CONFIG.imagesPerType * 2)) {
        console.warn('\n⚠️ Warning: Did not find the full 150 images. You may need to run this again or change the subreddits.');
    }

    console.log('\nGenerating schema.sql...');

    // Start building the SQL string
    let sql = `-- Auto-generated by fetchRedditImages.js
DROP TABLE IF EXISTS images;

CREATE TABLE images (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    url TEXT NOT NULL,
    type TEXT NOT NULL,
    explanation TEXT NOT NULL
);

-- Insert Images\n`;

    // Group into chunks of 5 for readability and execution
    const totalDays = Math.ceil(allImages.length / CONFIG.imagesPerDay);

    for (let i = 0; i < totalDays; i++) {
        const start = i * CONFIG.imagesPerDay;
        const dayImages = allImages.slice(start, start + CONFIG.imagesPerDay);

        if (dayImages.length === 0) break;

        sql += `\n-- Day ${i + 1}\nINSERT INTO images (url, type, explanation) VALUES \n`;

        const valueStrings = dayImages.map(img =>
            `('${img.url}', '${img.type}', '${img.explanation}')`
        );

        sql += valueStrings.join(',\n') + ';\n';
    }

    // Write to file
    fs.writeFileSync('schema.sql', sql, 'utf8');
    console.log('\n🎉 Successfully created schema.sql with live Reddit data!');
}

main();