DROP TABLE IF EXISTS images;

CREATE TABLE images (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                        url TEXT NOT NULL,
                        type TEXT NOT NULL,
                        explanation TEXT NOT NULL
);

-- Insert your Day 1 images
INSERT INTO images (url, type, explanation) VALUES
                                                ('https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=600&auto=format&fit=crop', 'Real', 'Captured by a photographer. Notice the natural skin texture and perfect pupil symmetry.'),
                                                ('https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?q=80&w=600&auto=format&fit=crop', 'AI', 'Generated by Midjourney v5. The background logic defies physics and the lighting is inconsistent.'),
                                                ('https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?q=80&w=600&auto=format&fit=crop', 'Real', 'A genuine photo of a cat. The fur complexity and depth of field are consistent with optical lenses.'),
                                                ('https://images.unsplash.com/photo-1614730341194-75c60740a2d3?q=80&w=600&auto=format&fit=crop', 'AI', 'AI generated concept art. The stars blend into the clouds in a way that suggests diffusion noise.'),
                                                ('https://images.unsplash.com/photo-1506905925346-21bda4d32df4?q=80&w=600&auto=format&fit=crop', 'Real', 'Real landscape photography. The geological formations match known locations in the Alps.');

-- You would add the rest of your 150 images here