-- Auto-generated by fetchRedditImages.js
DROP TABLE IF EXISTS images;

CREATE TABLE images (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    url TEXT NOT NULL,
    type TEXT NOT NULL,
    explanation TEXT NOT NULL
);

-- Insert Images

-- Day 1
INSERT INTO images (url, type, explanation) VALUES 
('https://i.redd.it/x6ivcn90hvgf1.jpeg', 'Real', 'Real photo by u/natefriesen on r/itookapicture. Original title: "ITAP of a deer"'),
('https://i.redd.it/dj0x82xxvqoc1.jpeg', 'AI', 'AI generated by u/Left-Plant2717 on r/midjourney. Original prompt/title: "What’s an obvious giveaway this is AI?"'),
('https://i.redd.it/nvdlren6n1c01.jpg', 'Real', 'Real photo by u/Jimmy_Scrambles on r/itookapicture. Original title: "ITAP of a Departing Aircraft."'),
('https://i.redd.it/byf52bbp186e1.png', 'AI', 'AI generated by u/Sprinkles-Pitiful on r/midjourney. Original prompt/title: "New player unlocked"'),
('https://i.redd.it/xf47hxl7wme71.jpg', 'Real', 'Real photo by u/SapperInTexas on r/itookapicture. Original title: "ITAP of a grape being lit up by a narrow sunbeam."');

-- Day 2
INSERT INTO images (url, type, explanation) VALUES 
('https://i.imgur.com/5wopYGv.jpg', 'Real', 'Real photo by u/hi7en on r/itookapicture. Original title: "ITAP of a Lion as it walked towards me."'),
('https://i.redd.it/no37d1dqay261.jpg', 'Real', 'Real photo by u/eat-mycorpse on r/itookapicture. Original title: "ITAP of the skyscrapers in Moscow"'),
('https://i.redd.it/17db3csnoaob1.jpg', 'AI', 'AI generated by u/ripirpy on r/midjourney. Original prompt/title: "Bro no way 💀"'),
('https://i.redd.it/vdpeswh4yw4a1.jpg', 'Real', 'Real photo by u/Wholesale_Grapefruit on r/itookapicture. Original title: "ITAP of a dog named Louie"'),
('https://i.redd.it/z62uowmcup981.jpg', 'Real', 'Real photo by u/BellaVerona on r/itookapicture. Original title: "ITAP on New Year’s Eve."');

-- Day 3
INSERT INTO images (url, type, explanation) VALUES 
('https://i.redd.it/x8n6uls5neqd1.jpeg', 'Real', 'Real photo by u/ryan101 on r/itookapicture. Original title: "ITAP of a Seattle sunset over two hours time "'),
('https://i.redd.it/zdr9ycdiziz71.jpg', 'Real', 'Real photo by u/Judsonbirch on r/itookapicture. Original title: "ITAP down a street in Japan"'),
('https://i.redd.it/frqi156655b61.jpg', 'Real', 'Real photo by u/jessiepoo5 on r/itookapicture. Original title: "ITAP on a train"'),
('https://i.redd.it/rpdw8po40ryd1.jpeg', 'Real', 'Real photo by u/MadTeemo on r/itookapicture. Original title: "ITAP of a couple of ducks"'),
('https://i.redd.it/vmbkazwc0gd01.jpg', 'Real', 'Real photo by u/derekrliang on r/itookapicture. Original title: "ITAP of the super blue blood moon"');

-- Day 4
INSERT INTO images (url, type, explanation) VALUES 
('https://i.redd.it/d8wrzkzu6dm31.jpg', 'Real', 'Real photo by u/[deleted] on r/itookapicture. Original title: "ITAP of dragging fingers over dew on roof of car"'),
('https://i.redd.it/2vsnrgfa4pg01.jpg', 'Real', 'Real photo by u/resh510 on r/itookapicture. Original title: "ITAP of a moody rainy day in Chicago"'),
('https://i.redd.it/x47o6204rrm51.jpg', 'Real', 'Real photo by u/Bobby_dazzler1217 on r/itookapicture. Original title: "ITAP of my son on a walk"'),
('https://i.redd.it/2r93zpicmxra1.png', 'AI', 'AI generated by u/[deleted] on r/midjourney. Original prompt/title: "Grandma and her demon"'),
('https://i.redd.it/c3w3x2vz6yz41.jpg', 'Real', 'Real photo by u/rgaya on r/itookapicture. Original title: "ITAP of a building reflected on a shattered mirror on the street."');

-- Day 5
INSERT INTO images (url, type, explanation) VALUES 
('https://i.redd.it/ta9oyn37swyz.jpg', 'Real', 'Real photo by u/Msjw1960 on r/itookapicture. Original title: "ITAP of a buck and his bird in the morning mist"'),
('https://i.redd.it/lc9xbqj7llbd1.jpeg', 'Real', 'Real photo by u/Snoo_39873 on r/itookapicture. Original title: "ITAP of my and my boyfriend’s hair tied together in a knot "'),
('https://i.redd.it/gktv0rj5x9i91.jpg', 'Real', 'Real photo by u/xcrimby on r/itookapicture. Original title: "ITAP of a crow looking at me"'),
('https://i.imgur.com/LX143G7.jpg', 'Real', 'Real photo by u/asria on r/itookapicture. Original title: "ITAP of my brother fishing in the fog during the golden hour."'),
('https://i.redd.it/c54rhxh2kz481.jpg', 'Real', 'Real photo by u/Awiworld on r/itookapicture. Original title: "ITAP of my son in snow light."');

-- Day 6
INSERT INTO images (url, type, explanation) VALUES 
('https://i.redd.it/0i5xs2t2y0n61.jpg', 'Real', 'Real photo by u/Rose7pt on r/itookapicture. Original title: "ITAP of train tracks at sunset"'),
('https://i.redd.it/sats0joha4x11.jpg', 'Real', 'Real photo by u/DBVickers on r/itookapicture. Original title: "ITAP after a tornado in Gum Creek Tennessee"'),
('https://i.redd.it/r7tkujno68b81.jpg', 'Real', 'Real photo by u/hairy_quadruped on r/itookapicture. Original title: "ITAP of the wing scales on a butterfly"'),
('https://i.redd.it/befw2buh4elz.jpg', 'Real', 'Real photo by u/cassie_dilla on r/itookapicture. Original title: "ITAP of a homeless but not hopeless pup at my work."'),
('https://i.redd.it/45de5gbhza6e1.jpeg', 'AI', 'AI generated by u/Fearnero17 on r/midjourney. Original prompt/title: "Straight Banger🔥🔥"');

-- Day 7
INSERT INTO images (url, type, explanation) VALUES 
('https://i.redd.it/p1hjqufdqux51.jpg', 'Real', 'Real photo by u/Craving2Create on r/itookapicture. Original title: "ITAP of the first Woman VP of US at Pride 2019"'),
('https://i.redd.it/2ra48lnqjndz.jpg', 'Real', 'Real photo by u/fuz_3d on r/itookapicture. Original title: "ITAP A Picture of A Puddle"'),
('https://i.redd.it/cgzeo8ztqga81.jpg', 'Real', 'Real photo by u/kot0vich on r/itookapicture. Original title: "ITAP of a ship frozen in ice"'),
('https://i.redd.it/5qxwxx1cyo091.jpg', 'Real', 'Real photo by u/jerseykin on r/itookapicture. Original title: "ITAP of my wife with a fishbowl on her head in front of our TV"'),
('https://i.redd.it/ad8ks416m4x91.jpg', 'Real', 'Real photo by u/ayitsphotography on r/itookapicture. Original title: "ITAP of a sunset and a powerline over 2 hours"');

-- Day 8
INSERT INTO images (url, type, explanation) VALUES 
('https://i.redd.it/mh4fw6avnt561.jpg', 'Real', 'Real photo by u/Zbowers1998 on r/itookapicture. Original title: "ITAP of the snow in NYC last night"'),
('https://i.redd.it/8f197boxwxlz.jpg', 'Real', 'Real photo by u/aiidancamp on r/itookapicture. Original title: "ITAP of my friends paddling a canoe"'),
('https://i.redd.it/j0v1iak01m5b1.png', 'AI', 'AI generated by u/InnoSang on r/midjourney. Original prompt/title: "If Snoop dogg was a white blond man from sweden"'),
('https://i.redd.it/ngstd2b0hcva1.jpg', 'AI', 'AI generated by u/IndifferentSpectat0r on r/midjourney. Original prompt/title: "One is a real photo and one is A.I. generated. Can you tell which is which?"'),
('https://i.redd.it/ydslkbvmvz0c1.jpg', 'Real', 'Real photo by u/alisonmiu91 on r/itookapicture. Original title: "ITAP of a rainbow in my backyard"');

-- Day 9
INSERT INTO images (url, type, explanation) VALUES 
('https://i.redd.it/wsedfnj1sbd71.jpg', 'Real', 'Real photo by u/That-Donkey on r/itookapicture. Original title: "ITAP of my girlfriend doing homework in NYC."'),
('https://i.redd.it/26x570j42ja61.jpg', 'Real', 'Real photo by u/adambulleyphoto on r/itookapicture. Original title: "ITAP Edinburgh Castle surrounded by fog"'),
('https://i.redd.it/u9cxuzsj6lda1.jpg', 'Real', 'Real photo by u/onewaymonkey on r/itookapicture. Original title: "ITAP of a man painting shoes on a Rome street"'),
('https://i.redd.it/2cnkjo5c5yf61.jpg', 'Real', 'Real photo by u/jesuislasagna on r/itookapicture. Original title: "ITAP of my dog Bear"'),
('https://i.redd.it/zbfnhcd1uf881.jpg', 'Real', 'Real photo by u/triptoverona on r/itookapicture. Original title: "ITAP of the Sunset inside an almost empty plane"');

-- Day 10
INSERT INTO images (url, type, explanation) VALUES 
('https://i.redd.it/ka4nmnnbivo01.jpg', 'Real', 'Real photo by u/lenkellui on r/itookapicture. Original title: "ITAP through a bench"'),
('https://i.redd.it/cb3tu7f6t35a1.jpg', 'Real', 'Real photo by u/theobenjamin_photo on r/itookapicture. Original title: "ITAP of a climber the moment she lost balance"'),
('https://i.redd.it/q2iq4oyddv1b1.png', 'AI', 'AI generated by u/fAIkout on r/midjourney. Original prompt/title: "Midjourney is now banning discussions about banned prompts lol"'),
('https://i.imgur.com/yJ0dE1Y.jpg', 'Real', 'Real photo by u/bearded_neck on r/itookapicture. Original title: "ITAP of some people walking in Hong Kong"'),
('https://i.redd.it/x6fnzf26526e1.jpeg', 'AI', 'AI generated by u/NineClaws on r/midjourney. Original prompt/title: "The Public Option"');

-- Day 11
INSERT INTO images (url, type, explanation) VALUES 
('https://i.redd.it/78r3ttko3nnz.jpg', 'Real', 'Real photo by u/timh0314 on r/itookapicture. Original title: "ITAP of sunset during fall equinox. Known here as Chicagohenge."'),
('https://i.imgur.com/DvRAbyG.jpg', 'Real', 'Real photo by u/Roverprimus on r/itookapicture. Original title: "ITAP of a shadow"'),
('https://i.redd.it/531gtosfxvq51.jpg', 'Real', 'Real photo by u/derryainsworth on r/itookapicture. Original title: "ITAP of a ship"'),
('https://i.redd.it/r5q9mk7c1vb81.jpg', 'Real', 'Real photo by u/rapgraves on r/itookapicture. Original title: "ITAP of myself lying between two lakes in South Australia"'),
('https://i.redd.it/p6rfiwyst2x51.jpg', 'Real', 'Real photo by u/anshul119 on r/itookapicture. Original title: "ITAP of two hikers in the Alps"');

-- Day 12
INSERT INTO images (url, type, explanation) VALUES 
('https://i.redd.it/moyyhvn3jw0c1.jpg', 'Real', 'Real photo by u/OkaTeluguAbbayi on r/itookapicture. Original title: "ITAP of a ruined temple in Rome"'),
('https://i.redd.it/3yxl6dr580g21.jpg', 'Real', 'Real photo by u/mattjunes on r/itookapicture. Original title: "ITAP of a VW Bus reflection"'),
('https://i.redd.it/afrmx8krtrv41.jpg', 'Real', 'Real photo by u/SamStephens on r/itookapicture. Original title: "ITAP of a red bell pepper"'),
('https://i.redd.it/uxv2nl74wo5b1.jpg', 'AI', 'AI generated by u/Hot-Combination-8377 on r/midjourney. Original prompt/title: "Real or AI generated?"'),
('https://i.redd.it/mcxwmaa8pena1.jpg', 'Real', 'Real photo by u/scarletheavens1 on r/itookapicture. Original title: "ITAP of my cats watching a sunset."');

-- Day 13
INSERT INTO images (url, type, explanation) VALUES 
('https://i.redd.it/5fofbfmqcgh71.jpg', 'Real', 'Real photo by u/alittlebrock on r/itookapicture. Original title: "ITAP of my wife and curious son in the rain."'),
('https://i.redd.it/n0k1h7k1yo251.jpg', 'Real', 'Real photo by u/SaintHuck on r/itookapicture. Original title: "ITAP of a broken electronic billboard"'),
('https://i.redd.it/alcxn4r32zc91.jpg', 'Real', 'Real photo by u/justerikfotos on r/itookapicture. Original title: "ITAP of a red sailboat with icebergs"'),
('https://i.imgur.com/JlnpdV2.jpg', 'Real', 'Real photo by u/Rage-Bacon on r/itookapicture. Original title: "ITAP of an empty road in Montana at sunrise"'),
('https://i.imgur.com/hxpI9wt.jpg', 'Real', 'Real photo by u/NookShotten on r/itookapicture. Original title: "ITAP on my flight home over Washington"');

-- Day 14
INSERT INTO images (url, type, explanation) VALUES 
('https://i.redd.it/s28279uvw0o41.jpg', 'Real', 'Real photo by u/GroundedSpaceMan on r/itookapicture. Original title: "ITAP of “Rush Hour” in Los Angeles during the first day of California’s shelter in place."'),
('https://c1.staticflickr.com/1/368/18346189410_88d4c767d8_c.jpg', 'Real', 'Real photo by u/PickleMunkey on r/itookapicture. Original title: "ITAP of a toy"'),
('https://i.redd.it/wzg0wq3v9y861.jpg', 'Real', 'Real photo by u/amybonforte on r/itookapicture. Original title: "ITAP on New Years Eve."'),
('https://i.redd.it/wf71a2dvvh6a1.jpg', 'Real', 'Real photo by u/TalentBurke on r/itookapicture. Original title: "ITAP of The Empire State Building"'),
('https://i.redd.it/30xyqf6gfsgb1.png', 'AI', 'AI generated by u/YabbaDabbaDoofus on r/midjourney. Original prompt/title: "Prompt was "A normal pair of human hands.""');

-- Day 15
INSERT INTO images (url, type, explanation) VALUES 
('https://i.redd.it/r0y40kdjux0c1.jpg', 'Real', 'Real photo by u/[deleted] on r/itookapicture. Original title: "ITAP of the Washington mountains from the sky"'),
('https://i.redd.it/iip6gyakj5v61.jpg', 'Real', 'Real photo by u/afgomez on r/itookapicture. Original title: "ITAP of a rebellious tulip"'),
('https://i.redd.it/hm41eym0r3i51.jpg', 'Real', 'Real photo by u/kmyfrks on r/itookapicture. Original title: "ITAP of strangers, lovers, and a family"'),
('https://i.redd.it/fjtqsonjqi491.jpg', 'Real', 'Real photo by u/safcbullyjr on r/itookapicture. Original title: "ITAP of a bush."'),
('https://i.redd.it/5d4uef596k5a1.jpg', 'Real', 'Real photo by u/PhotoMatt28 on r/itookapicture. Original title: "ITAP of some reeds in morning light"');

-- Day 16
INSERT INTO images (url, type, explanation) VALUES 
('https://i.imgur.com/2A0QPep.jpg', 'AI', 'AI generated by u/Echidnahh on r/midjourney. Original prompt/title: "POV: You’re a tourist who ignored the warnings, walking in the Australian bush"'),
('https://i.imgur.com/Y3FmIxP.jpg', 'Real', 'Real photo by u/TheItalianStallion64 on r/itookapicture. Original title: "ITAP of Florence through a mirror"'),
('https://i.redd.it/hdsr83j38gb71.jpg', 'Real', 'Real photo by u/Historical-Engine906 on r/itookapicture. Original title: "ITAP of myself in a car at night"'),
('https://i.redd.it/yh2hifxreyeb1.png', 'AI', 'AI generated by u/Genderfluxxd on r/midjourney. Original prompt/title: ""Paralysis Demon" ..that''s not what I meant midjourney.."'),
('https://i.redd.it/xsxrpheoc4c91.jpg', 'Real', 'Real photo by u/llzzies on r/itookapicture. Original title: "ITAP of a baby turtle at sunset"');

-- Day 17
INSERT INTO images (url, type, explanation) VALUES 
('https://i.redd.it/mor8t3oia1661.jpg', 'Real', 'Real photo by u/Sivll on r/itookapicture. Original title: "ITAP of static electricity between two fingers."'),
('https://i.redd.it/yud2nn4yfjoa1.jpg', 'Real', 'Real photo by u/Plasmazine on r/itookapicture. Original title: "ITAP of a turtle in a clear lake."'),
('https://i.redd.it/ozzjz292hi871.jpg', 'Real', 'Real photo by u/havefundiscovering on r/itookapicture. Original title: "ITAP of my girlfriend in South Iceland"'),
('https://i.redd.it/hg7vvte9xvg01.jpg', 'Real', 'Real photo by u/resh510 on r/itookapicture. Original title: "ITAP of my 2 friends at the museum of modern art, Chicago"'),
('https://i.redd.it/7kzka0pu2el61.jpg', 'Real', 'Real photo by u/DreamsOfAWanderer on r/itookapicture. Original title: "ITAP of my cat coming out of his hideout"');