import { renderHtml } from "./renderHtml";

export interface Env {
	DB: D1Database;
	/** Set via: wrangler secret put PASSWORD_SALT */
	PASSWORD_SALT?: string;
	/** Set via: wrangler vars or wrangler.json vars block */
	ADSENSE_ID?: string;
	/** Set via: wrangler secret put ADMIN_TOKEN */
	ADMIN_TOKEN?: string;
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

async function hashPassword(password: string, salt: string): Promise<string> {
	const msgUint8 = new TextEncoder().encode(password + salt);
	const hashBuffer = await crypto.subtle.digest('SHA-256', msgUint8);
	const hashArray = Array.from(new Uint8Array(hashBuffer));
	return hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
}

function getTodayUTC(): string {
	return new Date().toISOString().split('T')[0];
}

function getDateUTC(daysFromNow: number): string {
	const d = new Date();
	d.setUTCDate(d.getUTCDate() + daysFromNow);
	return d.toISOString().split('T')[0];
}

// ─── Scheduled: Fetch new images from configured sources ─────────────────────

async function fetchAndInsertImages(env: Env): Promise<void> {
	const REDDIT_UA = 'unvAIl-Game-ImageFetcher/2.0';
	// Rotate through time windows based on the current week number
	const TIME_WINDOWS = ['week', 'month', 'year', 'all'];
	const weekNum = Math.floor(Date.now() / (7 * 86400000));
	const timeWindow = TIME_WINDOWS[weekNum % TIME_WINDOWS.length];

	try {
		const sources = await env.DB.prepare(
			"SELECT id, source_type, image_type, config FROM image_sources WHERE is_active = 1"
		).all();

		let totalInserted = 0;

		for (const source of (sources.results || [])) {
			if (source.source_type !== 'reddit') continue;

			const config = JSON.parse(source.config as string);
			const subreddit = config.subreddit as string;
			const imageType = source.image_type as string;
			let after: string | null = null;
			let fetched = 0;

			// Fetch up to 3 pages (≤300 posts) per source
			for (let page = 0; page < 3; page++) {
				const apiUrl = `https://www.reddit.com/r/${subreddit}/top.json?t=${timeWindow}&limit=100${after ? `&after=${after}` : ''}`;

				try {
					const resp = await fetch(apiUrl, { headers: { 'User-Agent': REDDIT_UA } });
					if (!resp.ok) break;

					const json = await resp.json() as any;
					const posts: any[] = json?.data?.children || [];

					for (const post of posts) {
						const data = post.data;
						const imgUrl: string = data.url || '';
						if (!imgUrl.match(/\.(jpg|jpeg|png|webp)(\?.*)?$/i)) continue;

						// Skip duplicates
						const existing = await env.DB.prepare(
							"SELECT id FROM images WHERE url = ?"
						).bind(imgUrl).first();
						if (existing) continue;

						const author = data.author || 'unknown';
						const title = (data.title || '').replace(/'/g, "''");
						const explanation = imageType === 'Real'
							? `Real photo by u/${author} on r/${subreddit}. Original title: "${title}"`
							: `AI generated by u/${author} on r/${subreddit}. Original prompt/title: "${title}"`;

						await env.DB.prepare(
							"INSERT INTO images (url, type, explanation, fetched_at, is_active, use_count) VALUES (?, ?, ?, datetime('now'), 1, 0)"
						).bind(imgUrl, imageType, explanation).run();
						fetched++;
					}

					after = json?.data?.after ?? null;
					if (!after) break;

				} catch (err) {
					console.error(`Reddit fetch error (r/${subreddit}, page ${page + 1}):`, err);
					break;
				}
			}

			await env.DB.prepare(
				"UPDATE image_sources SET last_fetched_at = datetime('now') WHERE id = ?"
			).bind(source.id).run();

			console.log(`Fetched ${fetched} new images from r/${subreddit} (window: ${timeWindow})`);
			totalInserted += fetched;
		}

		console.log(`fetchAndInsertImages complete. Total new: ${totalInserted}`);
	} catch (err) {
		console.error('fetchAndInsertImages error:', err);
	}
}

// ─── Scheduled: Pre-populate daily_sets for upcoming days ────────────────────

async function prepopulateDailySets(env: Env, daysAhead: number = 14): Promise<void> {
	try {
		for (let d = 0; d < daysAhead; d++) {
			const playDate = getDateUTC(d);

			const existing = await env.DB.prepare(
				"SELECT play_date FROM daily_sets WHERE play_date = ?"
			).bind(playDate).first();
			if (existing) continue;

			// Alternate balance: even offset = 3 Real + 2 AI, odd = 2 Real + 3 AI
			const realCount = d % 2 === 0 ? 3 : 2;
			const aiCount = 5 - realCount;

			const realRows = await env.DB.prepare(
				"SELECT id FROM images WHERE is_active = 1 AND type = 'Real' ORDER BY use_count ASC, last_used_date ASC NULLS FIRST LIMIT 20"
			).all();
			const aiRows = await env.DB.prepare(
				"SELECT id FROM images WHERE is_active = 1 AND type = 'AI' ORDER BY use_count ASC, last_used_date ASC NULLS FIRST LIMIT 20"
			).all();

			const realPool = (realRows.results || []).map(r => r.id as number);
			const aiPool = (aiRows.results || []).map(r => r.id as number);

			if (realPool.length < realCount || aiPool.length < aiCount) {
				console.warn(`Insufficient images for ${playDate}. Real: ${realPool.length}/${realCount}, AI: ${aiPool.length}/${aiCount}`);
				continue;
			}

			// Shuffle pools and pick required count
			const shuffle = (arr: number[]) => [...arr].sort(() => Math.random() - 0.5);
			const selected = [
				...shuffle(realPool).slice(0, realCount),
				...shuffle(aiPool).slice(0, aiCount),
			];
			// Shuffle combined so types are mixed
			const combined = shuffle(selected);
			const imageIds = JSON.stringify(combined);

			await env.DB.prepare(
				"INSERT INTO daily_sets (play_date, image_ids, created_at) VALUES (?, ?, datetime('now'))"
			).bind(playDate, imageIds).run();

			// Track usage on each selected image
			for (const id of combined) {
				await env.DB.prepare(
					"UPDATE images SET use_count = use_count + 1, last_used_date = ? WHERE id = ?"
				).bind(playDate, id).run();
			}

			console.log(`Created daily_set for ${playDate}: [${combined.join(', ')}]`);
		}
	} catch (err) {
		console.error('prepopulateDailySets error:', err);
	}
}

// ─── Scheduled: Health-check — deactivate dead image URLs ────────────────────

async function healthCheckImages(env: Env): Promise<void> {
	try {
		// Sample up to 50 images not used recently
		const stale = await env.DB.prepare(
			`SELECT id, url FROM images
			 WHERE is_active = 1
			   AND (last_used_date IS NULL OR last_used_date < date('now', '-30 days'))
			 LIMIT 50`
		).all();

		let deactivated = 0;

		for (const img of (stale.results || [])) {
			try {
				const resp = await fetch(img.url as string, {
					method: 'HEAD',
					headers: { 'User-Agent': 'unvAIl-Game-Proxy/1.0' },
				});
				if ([403, 404, 410].includes(resp.status)) {
					await env.DB.prepare("UPDATE images SET is_active = 0 WHERE id = ?")
						.bind(img.id).run();
					deactivated++;
				}
			} catch {
				// Transient network error — leave active, try again next week
			}
		}

		console.log(`Health check done. Deactivated ${deactivated}/${stale.results?.length ?? 0} images.`);
	} catch (err) {
		console.error('healthCheckImages error:', err);
	}
}

// ─── Worker ───────────────────────────────────────────────────────────────────

export default {
	// ── Scheduled handler (cron triggers) ──────────────────────────────────
	async scheduled(event: ScheduledEvent, env: Env, ctx: ExecutionContext): Promise<void> {
		console.log(`Scheduled cron triggered: ${event.cron}`);
		switch (event.cron) {
			case '0 2 * * 0':   // Every Sunday 02:00 UTC — fetch new images
				ctx.waitUntil(fetchAndInsertImages(env));
				break;
			case '5 0 * * *':   // Every day 00:05 UTC — pre-populate next 14 days
				ctx.waitUntil(prepopulateDailySets(env, 14));
				break;
			case '0 3 * * 1':   // Every Monday 03:00 UTC — health-check dead URLs
				ctx.waitUntil(healthCheckImages(env));
				break;
			default:
				console.warn(`Unknown cron: ${event.cron}`);
		}
	},

	// ── HTTP handler ────────────────────────────────────────────────────────
	async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
		const url = new URL(request.url);
		const salt = env.PASSWORD_SALT || 'unvAIl_s3cr3t_salt';

		// ── Ads.txt ────────────────────────────────────────────────────────
		if (url.pathname === '/ads.txt') {
			const pub = env.ADSENSE_ID || 'ca-pub-7388329784955167';
			return new Response(`google.com, ${pub}, DIRECT, f08c47fec0942fa0`, {
				headers: { 'Content-Type': 'text/plain' }
			});
		}

		// ── Auth: Register ─────────────────────────────────────────────────
		if (url.pathname === '/api/auth/register' && request.method === 'POST') {
			try {
				const { email, password, guestId } = await request.json() as any;
				const hash = await hashPassword(password, salt);
				const token = crypto.randomUUID();

				const existingUser = await env.DB.prepare(
					"SELECT email, password_hash FROM users WHERE email = ?"
				).bind(email).first();

				const queries = [];

				if (existingUser) {
					if (!existingUser.password_hash || existingUser.password_hash === '') {
						queries.push(env.DB.prepare(
							"UPDATE users SET password_hash = ?, token = ? WHERE email = ?"
						).bind(hash, token, email));
					} else {
						return new Response(JSON.stringify({ error: 'Email already exists and has a password.' }), { status: 400 });
					}
				} else {
					queries.push(env.DB.prepare(
						"INSERT INTO users (email, password_hash, token) VALUES (?, ?, ?)"
					).bind(email, hash, token));
				}

				if (guestId) {
					const existingStats = await env.DB.prepare(
						"SELECT user_id FROM user_stats WHERE user_id = ?"
					).bind(email).first();
					if (!existingStats) {
						queries.push(env.DB.prepare("UPDATE user_stats SET user_id = ? WHERE user_id = ?").bind(email, guestId));
						queries.push(env.DB.prepare("DELETE FROM users WHERE email = ?").bind(guestId));
					} else {
						queries.push(env.DB.prepare("DELETE FROM user_stats WHERE user_id = ?").bind(guestId));
						queries.push(env.DB.prepare("DELETE FROM users WHERE email = ?").bind(guestId));
					}
				}

				await env.DB.batch(queries);
				return new Response(JSON.stringify({ success: true, email, token }), { headers: { 'Content-Type': 'application/json' } });
			} catch (e: any) {
				return new Response(JSON.stringify({ error: `Database Error: ${e.message}` }), { status: 500 });
			}
		}

		// ── Auth: Login ────────────────────────────────────────────────────
		if (url.pathname === '/api/auth/login' && request.method === 'POST') {
			try {
				const { email, password } = await request.json() as any;
				const hash = await hashPassword(password, salt);

				const user = await env.DB.prepare(
					"SELECT email FROM users WHERE email = ? AND password_hash = ?"
				).bind(email, hash).first();

				if (user) {
					const newToken = crypto.randomUUID();
					await env.DB.prepare("UPDATE users SET token = ? WHERE email = ?").bind(newToken, user.email).run();
					return new Response(JSON.stringify({ success: true, email: user.email, token: newToken }), { headers: { 'Content-Type': 'application/json' } });
				} else {
					return new Response(JSON.stringify({ error: 'Invalid email or password' }), { status: 401 });
				}
			} catch (e: any) {
				return new Response(JSON.stringify({ error: `Database Error: ${e.message}` }), { status: 500 });
			}
		}

		// ── Image Proxy ────────────────────────────────────────────────────
		if (url.pathname === '/api/image') {
			const id = url.searchParams.get('id');
			if (!id) return new Response('Missing ID', { status: 400 });

			try {
				const result = await env.DB.prepare(
					"SELECT url FROM images WHERE id = ? AND is_active = 1"
				).bind(id).first();

				if (!result || !result.url) return new Response('Not found', { status: 404 });

				const imageResponse = await fetch(result.url as string, {
					headers: { 'User-Agent': 'unvAIl-Game-Proxy/1.0' }
				});

				if (!imageResponse.ok) {
					// Mark the image as inactive if it returns a permanent error
					if ([403, 404, 410].includes(imageResponse.status)) {
						ctx.waitUntil(
							env.DB.prepare("UPDATE images SET is_active = 0 WHERE id = ?").bind(id).run()
						);
					}
					return new Response('Failed to fetch image', { status: 502 });
				}

				return new Response(imageResponse.body, {
					headers: {
						'Content-Type': imageResponse.headers.get('Content-Type') || 'image/jpeg',
						'Cache-Control': 'public, max-age=86400',
					},
				});
			} catch (e: any) {
				return new Response(e.message, { status: 500 });
			}
		}

		// ── Report Broken Image ────────────────────────────────────────────
		if (url.pathname === '/api/report-broken' && request.method === 'POST') {
			try {
				const { id } = await request.json() as any;
				if (!id) return new Response('Missing id', { status: 400 });
				// Soft-delete: mark inactive so it won't be served again
				await env.DB.prepare("UPDATE images SET is_active = 0 WHERE id = ?").bind(id).run();
				return new Response(JSON.stringify({ success: true }), { headers: { 'Content-Type': 'application/json' } });
			} catch (e: any) {
				return new Response(e.message, { status: 500 });
			}
		}

		// ── Reveal Answer ──────────────────────────────────────────────────
		if (url.pathname === '/api/reveal') {
			const id = url.searchParams.get('id');
			if (!id) return new Response('Missing ID', { status: 400 });

			try {
				const result = await env.DB.prepare(
					"SELECT type, explanation FROM images WHERE id = ?"
				).bind(id).first();
				if (!result) return new Response('Not found', { status: 404 });
				return new Response(JSON.stringify(result), { headers: { 'Content-Type': 'application/json' } });
			} catch (e: any) {
				return new Response(e.message, { status: 500 });
			}
		}

		// ── Get User Stats ─────────────────────────────────────────────────
		if (url.pathname === '/api/stats' && request.method === 'GET') {
			const userId = url.searchParams.get('userId');
			if (!userId) return new Response('Missing User ID', { status: 400 });

			try {
				const result = await env.DB.prepare(
					"SELECT * FROM user_stats WHERE user_id = ?"
				).bind(userId).first();
				return new Response(JSON.stringify(result || {}), { headers: { 'Content-Type': 'application/json' } });
			} catch (e: any) {
				return new Response(e.message, { status: 500 });
			}
		}

		// ── Save User Stats ────────────────────────────────────────────────
		if (url.pathname === '/api/stats' && request.method === 'POST') {
			try {
				const body = await request.json() as any;
				const { userId, played, wins, currentStreak, maxStreak, distribution, lastPlayedDate } = body;

				await env.DB.batch([
					env.DB.prepare(`INSERT INTO users (email) VALUES (?) ON CONFLICT (email) DO NOTHING`).bind(userId),
					env.DB.prepare(`
						INSERT INTO user_stats (user_id, played, wins, current_streak, max_streak, distribution, last_played_date)
						VALUES (?, ?, ?, ?, ?, ?, ?)
						ON CONFLICT (user_id) DO UPDATE SET
						played = excluded.played,
						wins = excluded.wins,
						current_streak = excluded.current_streak,
						max_streak = excluded.max_streak,
						distribution = excluded.distribution,
						last_played_date = excluded.last_played_date
					`).bind(userId, played, wins, currentStreak, maxStreak, JSON.stringify(distribution), lastPlayedDate),
				]);

				return new Response(JSON.stringify({ success: true }), { headers: { 'Content-Type': 'application/json' } });
			} catch (e: any) {
				console.error("D1 Error saving stats:", e.message);
				return new Response(e.message, { status: 500 });
			}
		}

		// ── Admin: Manual trigger ──────────────────────────────────────────
		if (url.pathname === '/api/admin/trigger' && request.method === 'POST') {
			const authHeader = request.headers.get('Authorization') || '';
			const adminToken = env.ADMIN_TOKEN;
			if (!adminToken || authHeader !== `Bearer ${adminToken}`) {
				return new Response(JSON.stringify({ error: 'Unauthorized' }), { status: 401 });
			}

			try {
				const body = await request.json() as any;
				const action: string = body.action || '';
				const daysAhead: number = body.daysAhead || 14;

				if (action === 'fetch') {
					ctx.waitUntil(fetchAndInsertImages(env));
					return new Response(JSON.stringify({ success: true, message: 'Image fetch started' }), { headers: { 'Content-Type': 'application/json' } });
				} else if (action === 'prepopulate') {
					ctx.waitUntil(prepopulateDailySets(env, daysAhead));
					return new Response(JSON.stringify({ success: true, message: `Daily set pre-population started (${daysAhead} days)` }), { headers: { 'Content-Type': 'application/json' } });
				} else if (action === 'healthcheck') {
					ctx.waitUntil(healthCheckImages(env));
					return new Response(JSON.stringify({ success: true, message: 'Health check started' }), { headers: { 'Content-Type': 'application/json' } });
				} else {
					return new Response(JSON.stringify({ error: 'Unknown action. Use: fetch | prepopulate | healthcheck' }), { status: 400 });
				}
			} catch (e: any) {
				return new Response(JSON.stringify({ error: e.message }), { status: 500 });
			}
		}

		// ── Admin: Pool stats ──────────────────────────────────────────────
		if (url.pathname === '/api/admin/stats' && request.method === 'GET') {
			const authHeader = request.headers.get('Authorization') || '';
			const adminToken = env.ADMIN_TOKEN;
			if (!adminToken || authHeader !== `Bearer ${adminToken}`) {
				return new Response(JSON.stringify({ error: 'Unauthorized' }), { status: 401 });
			}

			try {
				const [totalRow, activeRow, usedRow, setsRow] = await Promise.all([
					env.DB.prepare("SELECT COUNT(*) as n FROM images").first(),
					env.DB.prepare("SELECT COUNT(*) as n FROM images WHERE is_active = 1").first(),
					env.DB.prepare("SELECT COUNT(*) as n FROM images WHERE use_count > 0").first(),
					env.DB.prepare("SELECT COUNT(*) as n FROM daily_sets WHERE play_date >= date('now')").first(),
				]);
				return new Response(JSON.stringify({
					total:    totalRow?.n,
					active:   activeRow?.n,
					used:     usedRow?.n,
					upcomingSets: setsRow?.n,
				}), { headers: { 'Content-Type': 'application/json' } });
			} catch (e: any) {
				return new Response(e.message, { status: 500 });
			}
		}

		// ── Main Page ──────────────────────────────────────────────────────
		const today = getTodayUTC();
		const adsenseId = env.ADSENSE_ID || 'ca-pub-7388329784955167';

		try {
			let dailyImages: Record<string, unknown>[] = [];

			// Primary path: use the pre-populated daily_set for today
			const setRow = await env.DB.prepare(
				"SELECT image_ids FROM daily_sets WHERE play_date = ?"
			).bind(today).first();

			if (setRow?.image_ids) {
				const imageIds: number[] = JSON.parse(setRow.image_ids as string);
				if (imageIds.length > 0) {
					const placeholders = imageIds.map(() => '?').join(',');
					const { results } = await env.DB.prepare(
						`SELECT id FROM images WHERE id IN (${placeholders}) AND is_active = 1`
					).bind(...imageIds).all();

					// Preserve the order specified in daily_sets
					const available = new Set(results.map(r => r.id));
					dailyImages = imageIds
						.filter(id => available.has(id))
						.map(id => ({ id, url: `/api/image?id=${id}` }));
				}
			}

			// Fallback: legacy modulo rotation if no daily_set exists yet
			if (dailyImages.length === 0) {
				const START_DATE = new Date('2024-01-01T00:00:00Z');
				const dayIndex = Math.floor((Date.now() - START_DATE.getTime()) / 86400000);
				const limit = 5;

				const countRow = await env.DB.prepare(
					"SELECT COUNT(*) as total FROM images WHERE is_active = 1"
				).first();
				const totalImages = (countRow?.total as number) || 0;

				if (totalImages > 0) {
					const offset = (dayIndex % Math.floor(totalImages / limit)) * limit;
					const { results } = await env.DB.prepare(
						"SELECT id FROM images WHERE is_active = 1 LIMIT ? OFFSET ?"
					).bind(limit, offset).all();
					dailyImages = results.map(img => ({ id: img.id, url: `/api/image?id=${img.id}` }));
				}

				// Kick off set creation for today in the background
				ctx.waitUntil(prepopulateDailySets(env, 1));
			}

			return new Response(renderHtml(JSON.stringify(dailyImages), adsenseId), {
				headers: { "content-type": "text/html;charset=UTF-8" },
			});

		} catch (e: any) {
			return new Response(`Error connecting to D1 Database: ${e.message}`, { status: 500 });
		}
	},
};
